services:
  mysql:
    image: postgres:15.7
    container_name: book-note-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data # 데이터베이스 데이터가 저장될 위치
    networks:
      - my_network

volumes:
  postgres_data:

networks:
  my_network:
